<?php
/*
* Plugin Name : uc_banner_cbd01
*/

namespace Plugin\uc_banner_cbd01\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_banner_cbd01\Entity\uc_banner_cbd01Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_banner_cbd01 Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_banner_cbd01ConfigRepository extends AbstractRepository
{
    /**
     * uc_banner_cbd01Repository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_banner_cbd01Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_banner_cbd01Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
