<?php
/*
* Plugin Name : uc_banner
*/

namespace Plugin\uc_banner\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_banner\Entity\uc_bannerConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_banner Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_bannerConfigRepository extends AbstractRepository
{
    /**
     * uc_bannerRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_bannerConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_bannerConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
