<?php
/*
* Plugin Name : uc_banner
*/

namespace Plugin\uc_banner\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_banner\Entity\uc_bannerData;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_banner Data.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_bannerDataRepository extends AbstractRepository
{
    /**
     * uc_bannerDataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_bannerData::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_bannerData
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_bannerData
     */
    public function getImages()
    {
        return $this->findAll();
    }
}
