<?php
/*
* Plugin Name : uc_slide_sp
*/

namespace Plugin\uc_slide_sp\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide_sp\Entity\uc_slide_spConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide_sp Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slide_spConfigRepository extends AbstractRepository
{
    /**
     * uc_slide_spRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slide_spConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slide_spConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
