<?php
/*
* Plugin Name : uc_slide_sp
*/

namespace Plugin\uc_slide_sp\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide_sp\Entity\uc_slide_spData;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide_spImage Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slide_spDataRepository extends AbstractRepository
{
    /**
     * uc_slide_spDataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slide_spData::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slide_spData
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_slide_spData
     */
    public function getImages()
    {
        return $this->findAll();
    }

      /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_slideData
     */
    public function getRandomImages()
    {
        $images = $this->createQueryBuilder('p')
        //    ->orderBy('id')
            ->getQuery()
            ->getResult()
            ;

        shuffle($images);
        return $images;
    }
}
