<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Entity\PageCountdown;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CountDownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCountdownRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PageCountdown::class);
    }
    public function getAll()
    {
        $qb = $this->createQueryBuilder('pcd');
        $countdowns = $qb->getQuery()
            ->getResult();

        return $countdowns;
    }

    public function getCountdown()
    {
        $qb = $this->createQueryBuilder('pcd')->getQuery()->getSingleResult();
        return $qb;
    }

    public function save($countdown)
    {
        $em = $this->getEntityManager();
        $em->persist($countdown);
        $em->flush();
    }
}
