<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Entity\PageCountdownHistory;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CountDownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCountdownHistoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PageCountdownHistory::class);
    }
    public function getAll()
    {
        $qb = $this->createQueryBuilder('v');
        $categories = $qb->getQuery()
            ->getResult();

        return $categories;
    }
    public function getRewardsToday($customer)
    {
        return $customer ? $this->getRewardsByDay($customer, new \DateTime()) : 0;
    }
    public function getRewardsByDay($customer, $day)
    {
        $day->setTime(0, 0, 0, 0);
        $qb = $this->createQueryBuilder('pcd')
        ->where('pcd.customer = :customer')
        ->andWhere('pcd.created_at >= :day')
        ->setParameters([
            ':customer' => $customer,
            ':day' => $day,
        ])
        ->select('count(pcd.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
    public function reward($customer, $pageCountdown)
    {
        if (!$customer) {
            return null;
        }

        $currentPoint = $customer->getPoint();
        $newPoint = $currentPoint + $pageCountdown->getPoint();
        $customer->setPoint($newPoint);
        $historyReward = new PageCountdownHistory();
        $historyReward->setCustomer($customer);
        $historyReward->setCountdown($pageCountdown);
        $historyReward->setSecond($pageCountdown->getSecond());
        $historyReward->setPoint($pageCountdown->getPoint());
        $historyReward->setCreatedAt(new \DateTime());
        $historyReward->setUpdatedAt(new \DateTime());
        $this->getEntityManager()->persist($historyReward);
        $this->getEntityManager()->flush();
        return $historyReward;
    }

    public function getLastRewardByCustomer($customer)
    {
        if (!$customer) {
            return null;
        }

        $qb = $this->createQueryBuilder('pcd')
            ->where('pcd.customer = :customer')
            ->orderBy('pcd.created_at', 'DESC')
            ->setParameters([
                ':customer' => $customer,
            ])
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getHistoryReward($customer, $lastDategroup)
    {
        $dateDiff = 0;
        switch($lastDategroup) {
            case 1:
                $dateDiff = 7;
                break;
            case 2:
                $dateDiff = 30;
                break;
            default:
                $dateDiff = 0;
        }
        
        $histories = $this->createQueryBuilder('h')
            ->where('h.customer = :customer')
            ->orderBy('h.id', 'desc')
            ->setParameters([
                'customer' => $customer
            ]);

        if ($dateDiff) {
            $date = new \DateTime();
            $date->modify('-'.$dateDiff.' day');
            $date->setTime(0, 0, 0, 0);
            $histories->andWhere('h.created_at >= :date')
                ->setParameter(':date', $date);
        }

        return $histories;
    }
}
