<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Expr\GroupBy;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Master\OrderStatus;
use Eccube\Entity\Product;
use Eccube\Entity\ProductStock;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Plugin\ProductReview4\Entity\ProductReview;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;
    /**
     * @var CustomerRepository
     */
    private $customerReposistory;

    /**
     * @var OrderRepository
     */
    private $orderReposistory;

    /**
     * ProductRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EccubeConfig $eccubeConfig,
        CategoryRepository $categoryRepository,
        CustomerRepository $customerReposistory,
        OrderRepository $orderReposistory
    ) {
        parent::__construct($registry, Product::class);
        $this->queries = $queries;
        $this->eccubeConfig = $eccubeConfig;
        $this->categoryRepository = $categoryRepository;
        $this->customerReposistory = $customerReposistory;
        $this->orderReposistory = $orderReposistory;
    }

    /**
     * Find the Product with sorted ClassCategories.
     *
     * @param integer $productId
     *
     * @return Product
     */
    public function findWithSortedClassCategories($productId)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->addSelect(['pc', 'cc1', 'cc2', 'pi', 'pt'])
            ->innerJoin('p.ProductClasses', 'pc')
            ->leftJoin('pc.ClassCategory1', 'cc1')
            ->leftJoin('pc.ClassCategory2', 'cc2')
            ->leftJoin('p.ProductImage', 'pi')
            ->leftJoin('p.ProductTag', 'pt')
            ->where('p.id = :id')
            ->andWhere('pc.visible = :visible')
            ->setParameter('id', $productId)
            ->setParameter('visible', true)
            ->orderBy('cc1.sort_no', 'DESC')
            ->addOrderBy('cc2.sort_no', 'DESC');

        $product = $qb
            ->getQuery()
            ->getSingleResult();

        return $product;
    }

    /**
     * Find the Products with sorted ClassCategories.
     *
     * @param array $ids Product in ids
     * @param string $indexBy The index for the from.
     *
     * @return ArrayCollection|array
     */
    public function findProductsWithSortedClassCategories(array $ids, $indexBy = null)
    {
        if (count($ids) < 1) {
            return [];
        }
        $qb = $this->createQueryBuilder('p', $indexBy);
        $qb->addSelect(['pc', 'cc1', 'cc2', 'pi', 'pt', 'tr', 'ps'])
            ->innerJoin('p.ProductClasses', 'pc')
            // XXX Joined 'TaxRule' and 'ProductStock' to prevent lazy loading
            ->leftJoin('pc.TaxRule', 'tr')
            ->innerJoin('pc.ProductStock', 'ps')
            ->leftJoin('pc.ClassCategory1', 'cc1')
            ->leftJoin('pc.ClassCategory2', 'cc2')
            ->leftJoin('p.ProductImage', 'pi')
            ->leftJoin('p.ProductTag', 'pt')
            ->where($qb->expr()->in('p.id', $ids))
            ->andWhere('pc.visible = :visible')
            ->setParameter('visible', true)
            ->orderBy('cc1.sort_no', 'DESC')
            ->addOrderBy('cc2.sort_no', 'DESC');

        $products = $qb
            ->getQuery()
            ->useResultCache(true, $this->eccubeConfig['eccube_result_cache_lifetime_short'])
            ->getResult();

        return $products;
    }

    public function getProductsByBrandId($brandId) {
        $qb = $this->createQueryBuilder('p')->addSelect(['pi','pc','ps'])
                            ->innerJoin('p.ProductClasses', 'pc')
                            ->leftJoin('p.ProductImage', 'pi')
                            ->innerJoin('pc.ProductStock', 'ps')
                            ->where('p.brand = :brandId')
                            ->setParameter('brandId', $brandId);
        
        $products = $qb->getQuery()->getResult();

        return $products;
    }

    /**
     * get query builder.
     *
     * @param  array $searchData
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderBySearchData($searchData, $usrank=0, $isSupplier = false)
    {
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.Status = 1');

        $hiddenCategories = [];
        if (!$isSupplier) {
            $hiddenCategories = array_merge($hiddenCategories, $this->getSupplierCategories());
        }
        // category
        $categoryJoin = false;
        if (!empty($searchData['category_id']) && $searchData['category_id']) {
            if (isset($_GET['category_id']) && in_array($_GET['category_id'], $hiddenCategories)) {
                throw new NotFoundHttpException();
            }

            if (!empty($searchData['sub_category_id']) && $searchData['sub_category_id']) {
                $Categories = $searchData['sub_category_id']->getSelfAndDescendants();
            }else{
                $Categories = $searchData['category_id']->getSelfAndDescendants();
            }
            if ($Categories) {
                    $qb
                        ->innerJoin('p.ProductCategories', 'pct')
                        ->innerJoin('pct.Category', 'c')
                        ->andWhere($qb->expr()->in('pct.Category', ':Categories'))
                        ->setParameter('Categories', $Categories);
                $categoryJoin = true;
            }
        }
        //全商品商品一覧ページから指定のカテゴリーに属する商品を除外(CBD他) 20210723 kikuzawa
        else{
            //$cbd = array(22,27,28,14);
            //47が専用
            $cbd = array(22,27,28,14,39,47);//todo dev
            // KYO-152
            $cbd = array_merge($cbd, $hiddenCategories);
            $qb
                ->innerJoin('p.ProductCategories', 'pct')
                ->innerJoin('pct.Category', 'c')
                ->andWhere($qb->expr()->notIn('pct.Category', $cbd));
            $categoryJoin = true;
        }

        // name
        if (isset($searchData['name']) && StringUtil::isNotBlank($searchData['name'])) {
            $keywords = preg_split('/[\s　]+/u', str_replace(['%', '_'], ['\\%', '\\_'], $searchData['name']), -1, PREG_SPLIT_NO_EMPTY);

            foreach ($keywords as $index => $keyword) {
                $key = sprintf('keyword%s', $index);
                $qb
                    ->andWhere(sprintf('NORMALIZE(p.name) LIKE NORMALIZE(:%s) OR
                        NORMALIZE(p.search_word) LIKE NORMALIZE(:%s) OR
                        EXISTS (SELECT wpc%d FROM \Eccube\Entity\ProductClass wpc%d WHERE p = wpc%d.Product AND NORMALIZE(wpc%d.code) LIKE NORMALIZE(:%s))',
                        $key, $key, $index, $index, $index, $index, $key))
                    ->setParameter($key, '%'.$keyword.'%');
            }
        }

        // 会員種別（ダイヤモンド会員限定）
        if($usrank == 3){
            // 限定商品側を表示
            $qb->andWhere('p.OwnerProduct IS NULL');
        }else{
            // 限定商品をのぞいて表示
            $qb->leftJoin('Eccube\Entity\Product','sp','with','p.id = sp.owner_product_id')
                ->andWhere('sp.id is null')
            ;
        }
        // Order By
        // 価格低い順
        $config = $this->eccubeConfig;
        if (!empty($searchData['orderby']) && $searchData['orderby']->getId() == $config['eccube_product_order_price_lower']) {
            //@see http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html
            $qb->addSelect('MIN(pc.price02) as HIDDEN price02_min');
            $qb->innerJoin('p.ProductClasses', 'pc');
            $qb->andWhere('pc.visible = true');
            $qb->groupBy('p.id');
            $qb->orderBy('price02_min', 'ASC');
            $qb->addOrderBy('p.id', 'DESC');
        // 価格高い順
        } elseif (!empty($searchData['orderby']) && $searchData['orderby']->getId() == $config['eccube_product_order_price_higher']) {
            $qb->addSelect('MAX(pc.price02) as HIDDEN price02_max');
            $qb->innerJoin('p.ProductClasses', 'pc');
            $qb->andWhere('pc.visible = true');
            $qb->groupBy('p.id');
            $qb->orderBy('price02_max', 'DESC');
            $qb->addOrderBy('p.id', 'DESC');
        // 新着順
        } elseif (!empty($searchData['orderby']) && $searchData['orderby']->getId() == $config['eccube_product_order_newer']) {
            // 在庫切れ商品非表示の設定が有効時対応
            // @see https://github.com/EC-CUBE/ec-cube/issues/1998
            if ($this->getEntityManager()->getFilters()->isEnabled('option_nostock_hidden') == true) {
                $qb->innerJoin('p.ProductClasses', 'pc');
                $qb->andWhere('pc.visible = true');
            }
            $qb->orderBy('p.create_date', 'DESC');
            $qb->addOrderBy('p.id', 'DESC');
        } else {
            if ($categoryJoin === false) {
                $qb
                    ->leftJoin('p.ProductCategories', 'pct')
                    ->leftJoin('pct.Category', 'c');
            }
            $qb
                ->addOrderBy('p.id', 'DESC');
        }

        // Favorite
        if (!empty($searchData['favorite_user_id']) && $searchData['favorite_user_id']) {
            $Customer = $this->customerReposistory->find(['id' => $searchData['favorite_user_id']]);
            $qb
                ->innerJoin('p.CustomerFavoriteProducts', 'cfp')
                ->andWhere('cfp.Customer = :Customer')
                ->setParameter('Customer', $Customer);
        }

        if (!empty($searchData['brand']) && $searchData['brand']) {
            $qb
               ->andWhere('p.brand = :Brand')
               ->setParameter('Brand', $searchData['brand']);
        }

        return $this->queries->customize(QueryKey::PRODUCT_SEARCH, $qb, $searchData);
    }

    /**
     * get query builder.
     *
     * @param  array $searchData
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderBySearchDataForAdmin($searchData)
    {

        $qb = $this->createQueryBuilder('p')
            ->addSelect('pc', 'pi', 'tr', 'ps')
            ->innerJoin('p.ProductClasses', 'pc')
            ->leftJoin('p.ProductImage', 'pi')
            ->leftJoin('pc.TaxRule', 'tr')
            ->leftJoin('pc.ProductStock', 'ps');

            $exclusionTikTok = $searchData['isExclusionTikTok'] ?? false;
            if($exclusionTikTok && empty($searchData['category_id'])){ 

                //TikTok関係の商品は受注一覧に出てこないようにする
                // $exclusionCategory = array(47);
                // $qb->innerJoin('p.ProductCategories', 'pct')
                // ->innerJoin('pct.Category', 'c')
                //->andWhere($qb->expr()->notIn('pct.Category', $exclusionCategory));
                $qb->andWhere('p.name not like :name')
                ->setParameter('name', "%専用%");
            }
            

        // id
        if (isset($searchData['id']) && StringUtil::isNotBlank($searchData['id'])) {
            $id = preg_match('/^\d{0,10}$/', $searchData['id']) ? $searchData['id'] : null;
            $qb
                ->andWhere('p.id = :id OR p.name LIKE :likeid OR pc.code LIKE :likeid')
                ->setParameter('id', $id)
                ->setParameter('likeid', '%'.str_replace(['%', '_'], ['\\%', '\\_'], $searchData['id']).'%');
        }

        // code
        /*
        if (!empty($searchData['code']) && $searchData['code']) {
            $qb
                ->innerJoin('p.ProductClasses', 'pc')
                ->andWhere('pc.code LIKE :code')
                ->setParameter('code', '%' . $searchData['code'] . '%');
        }

        // name
        if (!empty($searchData['name']) && $searchData['name']) {
            $keywords = preg_split('/[\s　]+/u', $searchData['name'], -1, PREG_SPLIT_NO_EMPTY);
            foreach ($keywords as $keyword) {
                $qb
                    ->andWhere('p.name LIKE :name')
                    ->setParameter('name', '%' . $keyword . '%');
            }
        }
       */

        // category
        if (!empty($searchData['category_id']) && $searchData['category_id']) {
            $Categories = $searchData['category_id']->getSelfAndDescendants();
            if ($Categories) {
                $qb
                    ->innerJoin('p.ProductCategories', 'pct')
                    ->innerJoin('pct.Category', 'c')
                    ->andWhere($qb->expr()->in('pct.Category', ':Categories'))
                    ->setParameter('Categories', $Categories);
            }
        }

        // status
        if (!empty($searchData['status']) && $searchData['status']) {
            $qb
                ->andWhere($qb->expr()->in('p.Status', ':Status'))
                ->setParameter('Status', $searchData['status']);
        }

        // link_status
        if (isset($searchData['link_status']) && !empty($searchData['link_status'])) {
            $qb
                ->andWhere($qb->expr()->in('p.Status', ':Status'))
                ->setParameter('Status', $searchData['link_status']);
        }

        // stock status
        if (isset($searchData['stock_status'])) {
            $qb
                ->andWhere('pc.stock_unlimited = :StockUnlimited AND pc.stock = 0')
                ->setParameter('StockUnlimited', $searchData['stock_status']);
        }

        // stock status
        if (isset($searchData['stock']) && !empty($searchData['stock'])) {
            switch ($searchData['stock']) {
                case [ProductStock::IN_STOCK]:
                    $qb->andWhere('pc.stock_unlimited = true OR pc.stock > 0');
                    break;
                case [ProductStock::OUT_OF_STOCK]:
                    $qb->andWhere('pc.stock_unlimited = false AND pc.stock <= 0');
                    break;
                default:
                    // 共に選択された場合は全権該当するので検索条件に含めない
            }
        }

        // crate_date
        if (!empty($searchData['create_date_start']) && $searchData['create_date_start']) {
            $date = $searchData['create_date_start'];
            $qb
                ->andWhere('p.create_date >= :create_date_start')
                ->setParameter('create_date_start', $date);
        }

        if (!empty($searchData['create_date_end']) && $searchData['create_date_end']) {
            $date = clone $searchData['create_date_end'];
            $date = $date
                ->modify('+1 days');
            $qb
                ->andWhere('p.create_date < :create_date_end')
                ->setParameter('create_date_end', $date);
        }

        // update_date
        if (!empty($searchData['update_date_start']) && $searchData['update_date_start']) {
            $date = $searchData['update_date_start'];
            $qb
                ->andWhere('p.update_date >= :update_date_start')
                ->setParameter('update_date_start', $date);
        }
        if (!empty($searchData['update_date_end']) && $searchData['update_date_end']) {
            $date = clone $searchData['update_date_end'];
            $date = $date
                ->modify('+1 days');
            $qb
                ->andWhere('p.update_date < :update_date_end')
                ->setParameter('update_date_end', $date);
        }

        // Order By
        $qb
            ->orderBy('p.update_date', 'DESC');

        return $this->queries->customize(QueryKey::PRODUCT_SEARCH_ADMIN, $qb, $searchData);
    }

    public function getSupplierCategories()
    {
        $categories = $this->categoryRepository->getListCategoryForSupplier(env('SALON_SUPPLIER_CATEGORY'));
        if ($categories) {
            $categoryChildren = $categories[0]->getSelfAndDescendants();
            foreach ($categoryChildren as $categoryChild) {
                $hiddenCategories[] = $categoryChild->getId();
            }
        }

        return [];
    }
    public function getCustomerLastOrder($productId)
    {
        $qb = $this->orderReposistory->createQueryBuilder('o');
        $qb->select('o.email')
        ->innerJoin('o.OrderItems', 'oi')
        ->innerJoin('oi.Product', 'p')
        ->where('p.id = :productId')
        ->andWhere('o.OrderStatus IN (:statuses)')
        ->setParameter('productId', $productId)
        ->setParameter('statuses', [OrderStatus::NEW, OrderStatus::DELIVERED, OrderStatus::PAID])
        ->orderBy('o.order_date', 'DESC')
        ->setMaxResults(5);

        return $qb->getQuery()->getResult();
    }

    public function parseFAQs($input) {
        $lines = preg_split("/\r\n|\n|\r/", $input);
        $faqs = [];
        $currentQ = '';
        $currentA = '';
        $mode = '';

        foreach ($lines as $line) {
            $line = trim($line);
            if ($this->startsWith($line, 'Q:')) {
                if ($currentQ && $currentA) {
                    $faqs[] = ['question' => trim($currentQ), 'answer' => trim($currentA)];
                    $currentA = '';
                }
                $currentQ = substr($line, 2) . "\n";
                $mode = 'Q';
            } elseif ($this->startsWith($line, 'A:')) {
                $currentA = substr($line, 2) . "\n";
                $mode = 'A';
            } else {
                if ($mode === 'Q') {
                    $currentQ .= $line . "\n";
                } elseif ($mode === 'A') {
                    $currentA .= $line . "\n";
                }
            }
        }

        if ($currentQ && $currentA) {
            $faqs[] = ['question' => trim($currentQ), 'answer' => trim($currentA)];
        }

        return $faqs;
    }

    private function startsWith($haystack, $needle) {
        return strpos($haystack, $needle) === 0;
    }

    public function findTopSellingProducts(int $limit = 5) {
        $supplierCategories = $this->getSupplierCategories();

        $qb = $this->createQueryBuilder('p')
            ->select('p as product', 'SUM(oi.quantity) as totalQuantity')
            ->join('p.ProductClasses', 'pc')
            ->join('Eccube\Entity\OrderItem', 'oi', 'WITH', 'oi.ProductClass = pc.id')
            ->join('Eccube\Entity\Order', 'o', 'WITH', 'oi.Order = o.id')
            ->innerJoin('p.ProductCategories', 'pcat')
            ->where('o.OrderStatus IN (:statuses)')
            ->andWhere('p.Status = 1')
            ->setParameter('statuses', [5, 6])
            ->groupBy('p.id')
            ->orderBy('totalQuantity', 'DESC')
            ->setMaxResults($limit);

        if (!empty($supplierCategories)) {
            $qb->andWhere('pcat.Category NOT IN (:supplierCategories)')
            ->setParameter('supplierCategories', $supplierCategories);
        }

        $results = $qb->getQuery()->getResult();
        return array_map(function ($item) {
            return $item['product'];
        }, $results);
    }
}
