<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Entity\Video;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Video::class);
    }

    public function save($video)
    {
        $em = $this->getEntityManager();
        $em->persist($video);
        $em->flush($video);
    }

    public function delete($video)
    {
        $em = $this->getEntityManager();
        $em->remove($video);
        $em->flush($video);
    }

    public function getAllVideo()
    {
        $query = $this->createQueryBuilder('v')
            ->where('v.status = 1')
            ->orderBy('v.created_at', 'DESC');
        return $query->getQuery();
    }

    public function detail($id)
    {
        $video = $this->findOneBy([
            'id' => $id
        ]);

        return $video;

    }

    public function getVideoByFilterAll($customer, $filter)
    {
        $videos = $this->getVideosByFilterCategory($filter['category'])
            ->join('v.videoWatchPoints', 'vwp')
            ->andWhere('vwp.customer = :customer')
            ->orderBy('v.created_at', 'desc')
            ->setParameter('customer', $customer);

        if ($filter['watched'] == 'false') {
            $videos = $this->getVideoFilterWatchedIsFalse($videos)
                ->join('v.videoCategory', 'vc')
                ->andWhere('vc.id = :id')
                ->orderBy('v.created_at', 'desc')
                ->setParameter('id', $filter['category']);
        }

        return $videos;

    }

    public function getVideoByFilterWatched($customer, $filter)
    {
        $videos = $this->getVideoFilterWatchedIsTrue($customer);

        if ($filter == 'false') {
            $videos = $this->getVideoFilterWatchedIsFalse($videos);
        }

        return $videos;
    }

    public function getVideoFilterWatchedIsTrue($customer)
    {
        $videos = $this->createQueryBuilder('v')
            ->join('v.videoWatchPoints', 'vwp')
            ->where('vwp.customer = :customer')
            ->orderBy('v.created_at', 'desc')
            ->setParameter('customer', $customer);

        return $videos;
    }

    public function getVideoFilterWatchedIsFalse($watchedVideos)
    {
        $watchedVideos = $watchedVideos->getQuery()->getResult();
        $videoIds = array_map(function ($item) {
            return $item->id;
        }, $watchedVideos);
        $videos = $this->createQueryBuilder('v')
            ->where('v.id not in (:videoIds)')
            ->orderBy('v.created_at', 'desc')
            ->setParameter('videoIds', $videoIds);

        return $videos;
    }

    public function getVideosByFilterCategory($id)
    {
        $videos = $this->createQueryBuilder('v')
            ->join('v.videoCategory', 'vc')
            ->where('vc.id = :id')
            ->orderBy('v.created_at', 'desc')
            ->setParameter('id', $id);

        return $videos;
    }

    public function getVideoByFilter($customer, $filter)
    {
        if (isset($filter['category']) && isset($filter['watched']) && $customer) {
            $videos = $this->getVideoByFilterAll($customer, $filter);
        } else if (isset($filter['category'])) {
            $videos = $this->getVideosByFilterCategory($filter['category']);
        } else if (isset($filter['watched']) && $customer) {
            $videos = $this->getVideoByFilterWatched($customer, $filter['watched']);
        } else {
            $videos = $this->getAllVideo();
        }

        return $videos;
    }
}
