<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\DBAL\Exception\DriverException;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Eccube\Entity\Video;
use Eccube\Entity\VideoCategory;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCategoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, VideoCategory::class);
    }

    public function getAll()
    {
        $qb = $this->createQueryBuilder('v');
        $categories = $qb->getQuery()
            ->getResult();

        return $categories;
    }

    public function save($videoCategory)
    {
        $em = $this->getEntityManager();
        $em->persist($videoCategory);
        $em->flush($videoCategory);
    }

    public function delete($videoCategory)
    {
        if ($videoCategory->getCountVideo() > 0) {
            return false;
        } else {
            $em = $this->getEntityManager();
            $em->remove($videoCategory);
            $em->flush($videoCategory);
            return true;
        }
    }
}
