<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\VideoRelativeProduct;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRelativeProductRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, VideoRelativeProduct::class);
    }

    public function createVideoRelativeProduct($video, $product)
    {
        $videoRelativeProduct = new VideoRelativeProduct();
        $videoRelativeProduct->setVideo($video);
        $videoRelativeProduct->setProduct($product);
        $videoRelativeProduct->setCreatedAt(new \DateTime());
        $videoRelativeProduct->setUpdatedAt(new \DateTime());
        return $videoRelativeProduct;
    }

    public function removeVideoRelativeProduct($videoRelativeProduct, $video)
    {
        $video->removeVideoRelativeProducts($videoRelativeProduct);
        $this->getEntityManager()->remove($videoRelativeProduct);
    }
}
