<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Entity\VideoWatchPoint;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * VideoWatchPoint
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoWatchPointRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, VideoWatchPoint::class);
    }

    public function savePoint($video, $customer)
    {
        $currentPoint = $customer->getPoint();
        $newPoint = $currentPoint + $video->getVideoPointSetting()->getPoint();
        $videoWatchPoint = new VideoWatchPoint();
        $videoWatchPoint->setVideo($video);
        $videoWatchPoint->setVideoPointSetting($video->getVideoPointSetting());
        $videoWatchPoint->setCustomer($customer);
        $video->addVideoWatchPoints($videoWatchPoint);
        $video->addVideoWatchPoints($videoWatchPoint);
        $customer->setPoint($newPoint);
        $videoWatchPoint->setCreatedAt(new \DateTime());
        $videoWatchPoint->setUpdatedAt(new \DateTime());
        $this->getEntityManager()->persist($videoWatchPoint);
        $this->getEntityManager()->flush();
        return $videoWatchPoint;
    }

    public function getVideoPointHistoryByUser($customer)
    {
        $videos = $this->createQueryBuilder('vwp')
            ->where('vwp.customer = :customer')
            ->orderBy('vwp.created_at', 'desc')
            ->setParameters([
                ':customer' => $customer
            ]);

        return $videos;
    }

    public function countUserWatchVideo($customer, $video)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.customer = :customer')
            ->andWhere('v.video = :video')
            ->setParameters([
                ':customer' => $customer,
                ':video' => $video,
            ])
            ->select('count(v.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function removeVideo($video)
    {
        $videos = $this->createQueryBuilder('v')
            ->where('v.video = :video')
            ->setParameters([
                ':video' => $video
            ])
            ->getQuery()
            ->getResult();

        foreach ($videos as $video) {
            $this->getEntityManager()->remove($video);
            $this->getEntityManager()->flush($video);
        }
    }

    public function getVideoHistoryByFilter($customer, $filter)
    {
        if (isset($filter['category'])) {
            $videos = $this->getVideoHistoryByFilterCategory($filter['category'], $customer);
        } else {
            $videos = $this->getVideoPointHistoryByUser($customer);
        }

        return $videos;
    }

    public function getVideoHistoryByFilterCategory($id, $customer)
    {
        $videos = $this->createQueryBuilder('vwp')
            ->join('vwp.video', 'v')
            ->join('v.videoCategory', 'vc')
            ->where('vc.id = :id')
            ->andWhere('vwp.customer = :customer')
            ->orderBy('vwp.created_at', 'desc')
            ->setParameter('id', $id)
            ->setParameter('customer', $customer);

        return $videos;
    }

    public function getVideoIdWatchedByUser($customer)
    {
        $videos = $this->createQueryBuilder('vwp')
            ->join('vwp.video', 'v')
            ->where('vwp.customer = :customer')
            ->setParameter('customer', $customer)
            ->select('v.id');

        return $videos->getQuery()->getArrayResult();
    }
}
