<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\VideoPointSetting;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoPointSettingRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, VideoPointSetting::class);
    }

    public function createVideoPointSetting($video, $second, $point)
    {
        $videoPointSetting = new VideoPointSetting();
        $videoPointSetting->setVideo($video);
        $videoPointSetting->setSecond($second);
        $videoPointSetting->setPoint($point);
        $videoPointSetting->setCreatedAt(new \DateTime());
        $videoPointSetting->setUpdatedAt(new \DateTime());
        return $videoPointSetting;
    }

    public function isExistVideoPointSetting($video, $second, $point)
    {
        $videoPointSetting = $this->findOneBy([
            'video' => $video,
            'second' => $second,
            'point' => $point
        ]);

        return $videoPointSetting;
    }
}
