<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\MypageReceipt2\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\MypageReceipt2\Entity\MypageReceipt2Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MypageReceipt2 Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MypageReceipt2ConfigRepository extends AbstractRepository
{
    /**
     * MypageReceipt2ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MypageReceipt2Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|OsusumeProductConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
