<?php
/*
* Plugin Name : uc_banner_cbd02
*/

namespace Plugin\uc_banner_cbd02\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_banner_cbd02\Entity\uc_banner_cbd02Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_banner_cbd02 Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_banner_cbd02ConfigRepository extends AbstractRepository
{
    /**
     * uc_banner_cbd02Repository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_banner_cbd02Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_banner_cbd02Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
