<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) Takashi Otaki All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\EtunaNewItem\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\EtunaNewItem\Entity\EtunaNewItemConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * EtunaNewItem Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtunaNewItemConfigRepository extends AbstractRepository
{
    /**
     * EtunaNewItemConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, EtunaNewItemConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|EtunaNewItemConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
