<?php
/*
* Plugin Name : [code]
*/

namespace Plugin\[code]\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Eccube\Repository\CategoryRepository;
use Plugin\[code]\Entity\[code]Config;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * [code] Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class [code]ConfigRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $containerInterface;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManagerInterface;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    /**
     * [code]ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry,
        ContainerInterface $container,
        EntityManagerInterface $em,
        EccubeConfig $eccubeConfig
    )
    {
        parent::__construct($registry, [code]Config::class);
        $this->containerInterface = $container;
        $this->entityManagerInterface = $em;
        $this->eccubeConfig = $eccubeConfig;
    }

    /**
     * @param int $id
     *
     * @return null|[code]Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @return array
     */
    public function getProductRanking()
    {
        $Config = $this->entityManagerInterface->find([code]Config::class, 1);

        $category_id = $Config['category_id'];
        $display_num = $Config['display_num'];
        $display_order = $Config['display_order'];

        // カテゴリーのセット
        if( $category_id != 0 ){
            $Category = $this->containerInterface
                ->get(CategoryRepository::class)
                ->findOneBy(['id' => $category_id]);

            $children = $Category->getSelfAndDescendants();
            $categories = array();
            foreach ($children as $child) {
                $categories[] = $child['id'];
            }
        }

        $excludes = [8,3,7];

        $em = $this->containerInterface->get('doctrine.orm.entity_manager');
        $qb = $em->createQueryBuilder();

        // カテゴリ指定なし
        if( $category_id == 0){
            $qb
            ->select('SUM(od.price * od.quantity) as total,p.id')
            ->from('Eccube\Entity\OrderItem', 'od')
            ->leftJoin('Eccube\Entity\Product', 'p', 'WITH', 'p = od.Product')
            ->leftJoin('Eccube\Entity\Order', 'o', 'WITH', 'od.Order = o')
            ->andWhere('o.OrderStatus NOT IN (:excludes)')
            ->andWhere('p.Status = 1')
            ->setParameter(':excludes', $excludes)
            ->orderBy('total', 'DESC')
            ->groupBy('p.id');
        }
        // カテゴリに指定がある場合
        else{
            $qb
            ->select('SUM(od.price * od.quantity) as total,p.id')
            ->from('Eccube\Entity\OrderItem', 'od')
            ->leftJoin('Eccube\Entity\Product', 'p', 'WITH', 'p = od.Product')
            ->leftJoin('Eccube\Entity\Order', 'o', 'WITH', 'od.Order = o')
            ->leftJoin('Eccube\Entity\ProductCategory', 'c', 'WITH', 'c.product_id = p.id')
            ->andWhere('c.category_id IN (:category_id)')
            ->setParameter(':category_id', $categories)
            ->andWhere('o.OrderStatus NOT IN (:excludes)')
            ->andWhere('p.Status = 1')
            ->setParameter(':excludes', $excludes)
            ->orderBy('total', 'DESC')
            ->groupBy('p.id');
        }

        // 期間設定
        $Date = new \DateTime();
        $end = $Date->format("Y-m-d 23:59:59");
        if($display_order == '1'){
            $prev = "- 1 week";
        }elseif($display_order == '2'){
            $prev = "- 1 month";
        }elseif($display_order == '3'){
            $prev = "- 1 year";
        }else{
            $prev = "- 1 day";
        }
        $start = $Date->modify($prev)->format("Y-m-d 00:00:00");

        // 共通処理
        $qb
        ->andWhere('o.create_date >= :start')
        ->andWhere('o.create_date <= :end')
        ->setParameter(':start', $start)
        ->setParameter(':end', $end)
        ->setMaxResults($display_num);

        // エラー処理
        $result = array();
        try {
            $result = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            
        }

        $resultCategory = $this->unique_multidim_array($result, 'id');

        // 集計結果を配列化
        $Products = array();
        $i = 0;
        foreach ($resultCategory as $product) {
            if($product['id'] !== null ){
                $Products[$i] = $this->containerInterface->get(ProductRepository::class)->find($product['id']);
                $i++;
            }
        }

        return $Products;
    }

    /**
     * get config
     * @return array
     */
    public function get[code]Config()
    {
        $Config = $this->entityManagerInterface->find([code]Config::class, 1);
        return $Config;
    }

    private function unique_multidim_array($array, $key) { 
        $temp_array = array(); 
        $i = 0; 
        $key_array = array(); 
        
        foreach($array as $val) { 
            if (!in_array($val[$key], $key_array)) { 
                $key_array[$i] = $val[$key]; 
                $temp_array[$i] = $val; 
            } 
            $i++; 
        } 
        return $temp_array;
    } 
}
