<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\RelatedProduct4\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Repository\AbstractRepository;
use Plugin\RelatedProduct4\Entity\RelatedProduct;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * RelatedProductRepository.
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedProductRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $containerInterface;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManagerInterface;
    /**
     * RelatedProductRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry,
        ContainerInterface $container,
        EntityManagerInterface $em
    )
    {
        parent::__construct($registry, RelatedProduct::class);
        $this->containerInterface = $container;
        $this->entityManagerInterface = $em;
    }

    /**
     * @param Product
     *
     * @return Product
     */
    public function getReviewInfo($product){

        $rate = $this->containerInterface->get(\Plugin\ProductReview4\Repository\ProductReviewRepository::class)->getAvgAll($product);
        $product->review_ave = round($rate['recommend_avg']);
        $product->review_cnt = intval($rate['review_count']);
        return $product;
    }

}
