<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  2.0.3   |
    |              on 2021-09-17 16:10:28              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
namespace Plugin\AmazonPayV2\Controller\Admin;use Eccube\Controller\AbstractController;use Plugin\AmazonPayV2\Form\Type\Admin\ConfigType;use Plugin\AmazonPayV2\Repository\ConfigRepository;use Symfony\Component\Form\FormError;use Symfony\Component\Routing\Annotation\Route;use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\Validator\Constraints as Assert;use Symfony\Component\Validator\Validator\ValidatorInterface;class ConfigController extends AbstractController{protected $validator;protected $configRepository;public function __construct(ValidatorInterface $validator, ConfigRepository $configRepository){$this->validator = $validator;$this->configRepository = $configRepository;}    
/**
* @Route("/%eccube_admin_route%/amazon_pay_v2/config", name="amazon_pay_v2_admin_config")
* @Template("@AmazonPayV2/admin/config.twig")
*/
public function index(Request $request){goto fEJ1f;PZVW7:return $this->redirectToRoute('amazon_pay_v2_admin_config');goto Xj11O;LmNPK:goto q1OS0;goto djtTJ;qB0_0:$privateKeyPath = $this->getParameter('kernel.project_dir') . '/' . $Config->getPrivateKeyPath();goto fEBGW;iD1NE:IP2At:goto BgzPK;V9_2X:$form['prod_key']->addError(new FormError('本番環境切り替えキーは有効なキーではありません。'));goto iD1NE;Xj11O:qYfWK:goto LHeGB;ngu1L:DYk9j:goto ihjwA;zUyeR:$this->entityManager->flush($Config);goto HjP1H;r1kIj:return ['form' => $form->createView(), 'testAccount' => $testAccount];goto QMN4o;ExpJG:$testAccount = $this->eccubeConfig['amazon_pay_v2']['test_account'];goto r1kIj;Y1xQc:if (!($form->isSubmitted() && $form->isValid())) {goto W_PLZ;}goto TFWDk;gUiFZ:XABs7:goto b9c2b;GwAcb:q1OS0:goto ngu1L;oWybQ:foreach ($errors as $error) {$messages[] = $error->getMessage();oZ6zS:}goto SOj4i;JoXMs:$errors = $this->validator->validate($prod_key, [new Assert\NotBlank()]);goto t42il;LHeGB:W_PLZ:goto ExpJG;eFaLw:$form['private_key_path']->addError(new FormError('プライベートキーパスの先頭に"/"は利用できません'));goto yvJfe;qT6IT:$this->entityManager->persist($Config);goto zUyeR;uia0E:$prod_key = $Config->getProdKey();goto JoXMs;wn2qD:if (!($Config->getAmazonAccountMode() == $this->eccubeConfig['amazon_pay_v2']['account_mode']['owned'])) {goto DYk9j;}goto qB0_0;b9c2b:JPMnz:goto wn2qD;l83WV:if (!is_file($privateKeyPath) || file_exists($privateKeyPath) === false) {goto TSx3n;}goto LmNPK;rAO7e:$form['prod_key']->addError(new FormError($messages[0]));goto gUiFZ;fEJ1f:$Config = $this->configRepository->get(true);goto EksIM;HjP1H:$this->addSuccess('amazon_pay_v2.admin.save.success', 'admin');goto PZVW7;SOj4i:HDMjJ:goto rAO7e;djtTJ:ll4dl:goto eFaLw;FTKj9:if (!($Config->getEnv() == $this->eccubeConfig['amazon_pay_v2']['env']['prod'])) {goto JPMnz;}goto uia0E;TFWDk:$Config = $form->getData();goto FTKj9;ihjwA:if (!($form->isSubmitted() && $form->isValid())) {goto qYfWK;}goto qT6IT;oY1by:if (password_verify($prod_key, '$2y$10$m3aYrihBaIKarlrmI39tGORK4fFBC7cWoSLFy6jkMpT7IduYVsVtO')) {goto IP2At;}goto V9_2X;lqmzb:$form['private_key_path']->addError(new FormError('プライベートキーファイルが見つかりません。'));goto GwAcb;Uvgoq:xBYYg:goto oWybQ;EksIM:$form = $this->createForm(ConfigType::class, $Config);goto lt3Kq;fEBGW:if (mb_substr($Config->getPrivateKeyPath(), 0, 1) == '/') {goto ll4dl;}goto l83WV;H45Js:TSx3n:goto lqmzb;t42il:if ($errors->count() != 0) {goto xBYYg;}goto oY1by;BgzPK:goto XABs7;goto Uvgoq;lt3Kq:$form->handleRequest($request);goto Y1xQc;yvJfe:goto q1OS0;goto H45Js;QMN4o:}}