<?php
/*
* Plugin Name : uc_slide
*/

namespace Plugin\uc_slide\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide\Entity\uc_slideData;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slideImage Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slideDataRepository extends AbstractRepository
{
    /**
     * uc_slideDataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slideData::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slideData
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_slideData
     */
    public function getImages()
    {
        return $this->findAll();
    }
}
