<?php
/*
* Plugin Name : uc_slide
*/

namespace Plugin\uc_slide\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide\Entity\uc_slideConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slideConfigRepository extends AbstractRepository
{
    /**
     * uc_slideRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slideConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slideConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
