<?php
/*
* Plugin Name : [code]
*/

namespace Plugin\[code]\Repository;

use Eccube\Common\EccubeConfig;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\NewsRepository;
use Plugin\[code]\Entity\[code]Config;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * [code] Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class [code]ConfigRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $containerInterface;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    /**
     * [code]ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry,
        ContainerInterface $container
    )
    {
        parent::__construct($registry, [code]Config::class);
        $this->containerInterface = $container;
    }

    /**
     * @param int $id
     *
     * @return null|[code]Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
