<?php
/*
* Plugin Name : UICube
*/

namespace Plugin\UICube\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\UICube\Entity\UICubeConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * UICube Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UICubeRepository extends AbstractRepository
{
    /**
     * UICubeRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, UICubeConfig::class);
    }


    /**
     * @param int $id
     *
     * @return null|UICubeConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
