<?php
/*
* Plugin Name : [code]
*/

namespace Plugin\[code]\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Eccube\Repository\CategoryRepository;
use Plugin\[code]\Entity\[code]Config;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * [code] Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class [code]ConfigRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $containerInterface;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManagerInterface;

    /**
     * [code]ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry,
        ContainerInterface $container,
        EntityManagerInterface $em
    )
    {
        parent::__construct($registry, [code]Config::class);
        $this->containerInterface = $container;
        $this->entityManagerInterface = $em;
    }

    /**
     * @param int $id
     *
     * @return null|[code]Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @return array
     */
    public function getNewProducts()
    {
        $Config = $this->entityManagerInterface->find([code]Config::class, 1);

        $category_id = $Config['category_id'];
        $tag_id = $Config['tag_id'];
        $display_num = $Config['display_num'];

        if( $category_id != 0 ){
            $Category = $this->containerInterface
                ->get(CategoryRepository::class)
                ->findOneBy(['id' => $category_id]);

            $children = $Category->getSelfAndDescendants();
            $categories = array();
            foreach ($children as $child) {
                $categories[] = $child['id'];
            }
        }

        // カテゴリ、タグともに指定なし
        if( $category_id == 0 && $tag_id == 0){
            $productRepository = $this->containerInterface->get(ProductRepository::class);
            $Products = $productRepository->createQueryBuilder('p')
                ->orderBy('p.create_date', 'DESC')
                ->andWhere('p.Status = 1')
                ->setMaxResults($display_num)
                ->getQuery()
                ->getResult();
        }
        // どちらかに指定がある場合
        else{
            $em = $this->containerInterface->get('doctrine.orm.entity_manager');
            $qb = $em->createQueryBuilder();
            $qb->select('p.id');

            // カテゴリに指定がある場合
            if( $tag_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('c.product_id = p.id');
            }
            // タグに指定がある場合
            elseif( $category_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductTag', 't')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id)
                ->andWhere('t.Product = p.id');
            }
            // 両方に指定がある場合
            else{
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p', 'WITH', 'p.id = c.product_id')
                ->leftJoin('Eccube\Entity\ProductTag', 't', 'WITH', 't.Product = p.id')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id);
            }

            // 表示順序
            if( $Config['display_order'] == 0 ){
                $qb->orderBy('p.create_date', 'DESC');
            }else{
                $qb->orderBy('p.update_date', 'DESC');
            }

            // 共通処理
            $qb
            ->andWhere('p.Status = 1')
            ->setMaxResults($display_num);

            // エラー処理
            $result = array();
            try {
                $result = $qb->getQuery()->getResult();
            } catch (NoResultException $e) {
                
            }

            $resultCategory = $this->unique_multidim_array($result, 'id');

            // 集計結果を配列化
            $Products = array();
            $i = 0;
            foreach ($resultCategory as $product) {
                if($product['id'] !== null ){
                    $Products[$i] = $this->containerInterface->get(ProductRepository::class)->find($product['id']);
                    $i++;
                }
            }
        }

        return $Products;
    }

    /**
     * get config
     * @return array
     */
    public function get[code]Config()
    {
        $Config = $this->entityManagerInterface->find([code]Config::class, 1);
        return $Config;
    }

    private function unique_multidim_array($array, $key) { 
        $temp_array = array(); 
        $i = 0; 
        $key_array = array(); 
        
        foreach($array as $val) { 
            if (!in_array($val[$key], $key_array)) { 
                $key_array[$i] = $val[$key]; 
                $temp_array[$i] = $val; 
            } 
            $i++; 
        } 
        return $temp_array;
    } 
}
