<?php
/**
 * This file is part of BundleSale4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 * https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\BundleSale4\Tests\Web;


use Eccube\Entity\Product;
use Eccube\Entity\ProductClass;
use Eccube\Tests\Web\AbstractShoppingControllerTestCase;
use Plugin\BundleSale4\Entity\BundleItem;

class ShoppingControllerTest extends AbstractShoppingControllerTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testセット商品とセット商品に含まれる商品の在庫が1個で同時購入した場合()
    {
        $product = $this->createProduct();
        /** @var ProductClass $productClass */
        foreach ($product->getProductClasses() as $productClass) {
            $productClass->setStockUnlimited(false);
            $productClass->setStock(1);
            $productClass->getProductStock()->setStock(1);
            $this->entityManager->persist($productClass);
        }
        $this->entityManager->flush();

        $setProduct = $this->createSetProduct($product);

        $customer = $this->createCustomer();

        // カート画面
        $this->scenarioCartIn($customer, $product->getProductClasses()->first()->getId());
        $this->scenarioCartIn($customer, $setProduct->getProductClasses()->first()->getId());

        // 手続き画面
        $crawler = $this->scenarioConfirm($customer);
        $this->expected = 'ご注文手続き';
        $this->actual = $crawler->filter('.ec-pageHeader h1')->text();
        $this->verify();

        // 確認画面
        $crawler = $this->scenarioComplete($customer, $this->generateUrl('shopping_confirm'));
        $this->expected = 'ご注文内容のご確認';
        $this->actual = $crawler->filter('.ec-pageHeader h1')->text();
        $this->verify();

        // 完了画面
        $this->scenarioCheckout($customer);
        self::assertTrue($this->client->getResponse()->isRedirect($this->generateUrl('shopping_error')));

        $crawler = $this->client->followRedirect();

        $productClass = $product->getProductClasses()->first();

        $message = $crawler->filter('.ec-alert-warning__text')->text();
        self::assertSame(sprintf("「%s」の在庫が足りません。", $productClass->formattedProductName()), trim($message));
    }

    /**
     * セット商品を作成
     *
     * @param Product $product
     * @param int $quantity
     * @return Product
     */
    private function createSetProduct(Product $product, $quantity = 1)
    {
        $setProduct = $this->createProduct('セット商品', 0);

        foreach ($product->getProductClasses() as $productClass) {
            $bundleItem = new BundleItem();
            $bundleItem
                ->setProduct($product)
                ->setProductClass($productClass)
                ->setQuantity($quantity);
            $setProduct->addBundleItem($bundleItem);
        }
        $this->entityManager->persist($setProduct);
        $this->entityManager->flush();

        return $setProduct;
    }
}
