<?php
/*
* Plugin Name : uc_slide_cbd
*/

namespace Plugin\uc_slide_cbd\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide_cbd\Entity\uc_slide_cbdData;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide_cbdImage Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slide_cbdDataRepository extends AbstractRepository
{
    /**
     * uc_slide_cbdDataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slide_cbdData::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slide_cbdData
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_slide_cbdData
     */
    public function getImages()
    {
        return $this->findAll();
    }
}
