<?php
/*
* Plugin Name : uc_slide_cbd
*/

namespace Plugin\uc_slide_cbd\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide_cbd\Entity\uc_slide_cbdConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide_cbd Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slide_cbdConfigRepository extends AbstractRepository
{
    /**
     * uc_slide_cbdRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slide_cbdConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slide_cbdConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
