<?php
/*
* Plugin Name : uc_newitems
*/

namespace Plugin\uc_newitems\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Eccube\Repository\CategoryRepository;
use Plugin\uc_newitems\Entity\uc_newitemsConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * uc_newitems Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_newitemsConfigRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $containerInterface;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManagerInterface;

    /**
     * uc_newitemsConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry,
        ContainerInterface $container,
        EntityManagerInterface $em
    )
    {
        parent::__construct($registry, uc_newitemsConfig::class);
        $this->containerInterface = $container;
        $this->entityManagerInterface = $em;
    }

    /**
     * @param int $id
     *
     * @return null|uc_newitemsConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @return array
     */
    public function getNewProducts($isSupplier = false)
    {
        $Config = $this->entityManagerInterface->find(uc_newitemsConfig::class, 1);

        $category_id = $Config['category_id'];
        $tag_id = $Config['tag_id'];
        $display_num = $Config['display_num'];

        if( $category_id != 0 ){
            $Category = $this->containerInterface
                ->get(CategoryRepository::class)
                ->findOneBy(['id' => $category_id]);

            $children = $Category->getSelfAndDescendants();
            $categories = array();
            foreach ($children as $child) {
                $categories[] = $child['id'];
            }
        }
        //CBD関連のカテゴリーをセット 20210723 kikuzawa
        else{
            $cbd = array(22,27,28);
            $categories = array();
            //mukai カテゴリがnullでエラーが出ていたので修正
            // foreach ($cbd as $cid) {
            //     $Category = $this->containerInterface
            //         ->get(CategoryRepository::class)
            //         ->findOneBy(['id' => $cid]);

            //     $children = $Category->getSelfAndDescendants();
            //     foreach ($children as $child) {
            //         $categories[] = $child['id'];
            //     }
            // }

            if (!$isSupplier) {
                $categories = array_merge($categories, $this->getSupplierCategories());
            }
        }

        $em = $this->containerInterface->get('doctrine.orm.entity_manager');
        $qb = $em->createQueryBuilder();
        $qb->select('p.id');

        // カテゴリ、タグともに指定なし
        //CBD関連の商品は除外 20210723 kikuzawa
        if( $category_id == 0 && $tag_id == 0){
            $qb
            ->from('Eccube\Entity\ProductCategory', 'c')
            ->leftJoin('Eccube\Entity\Product', 'p')
            ->andWhere('c.category_id NOT IN (:category_id)')
            ->setParameter(':category_id', $categories)
            ->andWhere('c.product_id = p.id');
        }
        // どちらかに指定がある場合
        else{
            // カテゴリに指定がある場合
            if( $tag_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('c.product_id = p.id');
            }
            // タグに指定がある場合
            elseif( $category_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductTag', 't')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id)
                ->andWhere('t.Product = p.id');
            }
            // 両方に指定がある場合
            else{
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p', 'WITH', 'p.id = c.product_id')
                ->leftJoin('Eccube\Entity\ProductTag', 't', 'WITH', 't.Product = p.id')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id);
            }
        }

        // 表示順序
        if( $Config['display_order'] == 0 ){
            $qb->orderBy('p.create_date', 'DESC');
        }else{
            $qb->orderBy('p.update_date', 'DESC');
        }

        // 共通処理
        $qb
        ->andWhere('p.Status = 1')
        ->setMaxResults($display_num);

        // エラー処理
        $result = array();
        try {
            $result = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {

        }

        $resultCategory = $this->unique_multidim_array($result, 'id');

        // 集計結果を配列化
        $Products = array();
        $i = 0;
        foreach ($resultCategory as $product) {
            if($product['id'] !== null ){
                $Products[$i] = $this->containerInterface->get(ProductRepository::class)->find($product['id']);
                $i++;
            }
        }

        foreach ($Products as $i => $product) {
            $rate = $this->containerInterface->get(\Plugin\ProductReview4\Repository\ProductReviewRepository::class)->getAvgAll($product);
            $product->review_ave = round($rate['recommend_avg']);
            $product->review_cnt = intval($rate['review_count']);
        //    $Products[$i] = $product;
        }


        return $Products;
    }

    /**
     * get config
     * @return array
     */
    public function getuc_newitemsConfig()
    {
        $Config = $this->entityManagerInterface->find(uc_newitemsConfig::class, 1);
        return $Config;
    }

    private function unique_multidim_array($array, $key) { 
        $temp_array = array(); 
        $i = 0; 
        $key_array = array(); 
        
        foreach($array as $val) { 
            if (!in_array($val[$key], $key_array)) { 
                $key_array[$i] = $val[$key]; 
                $temp_array[$i] = $val; 
            } 
            $i++; 
        } 
        return $temp_array;
    } 


/**
     * @return array
     */
    public function getUrankProducts()
    {
        $Config = $this->entityManagerInterface->find(uc_newitemsConfig::class, 1);

        //$category_id = $Config['category_id'];
        $category_id = 48;// ダイヤモンドメンバー限定
        $tag_id = $Config['tag_id'];
        $display_num = $Config['display_num'];

        
        if( $category_id != 0 ){
            $Category = $this->containerInterface
                ->get(CategoryRepository::class)
                ->findOneBy(['id' => $category_id]);

            $children = $Category->getSelfAndDescendants();
            $categories = array();
            foreach ($children as $child) {
                $categories[] = $child['id'];
            }
        }


        $em = $this->containerInterface->get('doctrine.orm.entity_manager');
        $qb = $em->createQueryBuilder();
        $qb->select('p.id');

        // カテゴリ、タグともに指定なし
        //CBD関連の商品は除外 20210723 kikuzawa
        if( $category_id == 0 && $tag_id == 0){
            $qb
            ->from('Eccube\Entity\ProductCategory', 'c')
            ->leftJoin('Eccube\Entity\Product', 'p')
            ->andWhere('c.category_id NOT IN (:category_id)')
            ->setParameter(':category_id', $categories)
            ->andWhere('c.product_id = p.id');
        }
        // どちらかに指定がある場合
        else{
            // カテゴリに指定がある場合
            if( $tag_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('c.product_id = p.id');
            }
            // タグに指定がある場合
            elseif( $category_id == 0 ){
                $qb
                ->from('Eccube\Entity\ProductTag', 't')
                ->leftJoin('Eccube\Entity\Product', 'p')
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id)
                ->andWhere('t.Product = p.id');
            }
            // 両方に指定がある場合
            else{
                $qb
                ->from('Eccube\Entity\ProductCategory', 'c')
                ->leftJoin('Eccube\Entity\Product', 'p', 'WITH', 'p.id = c.product_id')
                ->leftJoin('Eccube\Entity\ProductTag', 't', 'WITH', 't.Product = p.id')
                ->andWhere('c.category_id IN (:category_id)')
                ->setParameter(':category_id', $categories)
                ->andWhere('t.Tag = :tag_id')
                ->setParameter(':tag_id', $tag_id);
            }
        }

        // 表示順序
        if( $Config['display_order'] == 0 ){
            $qb->orderBy('p.create_date', 'DESC');
        }else{
            $qb->orderBy('p.update_date', 'DESC');
        }

        // 共通処理
        $qb
        ->andWhere('p.Status = 1')
        ->setMaxResults($display_num);

        // エラー処理
        $result = array();
        try {
            $result = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {

        }

        $resultCategory = $this->unique_multidim_array($result, 'id');

        // 集計結果を配列化
        $Products = array();
        $i = 0;
        foreach ($resultCategory as $product) {
            if($product['id'] !== null ){
                $Products[$i] = $this->containerInterface->get(ProductRepository::class)->find($product['id']);
                $i++;
            }
        }

        foreach ($Products as $i => $product) {
            $rate = $this->containerInterface->get(\Plugin\ProductReview4\Repository\ProductReviewRepository::class)->getAvgAll($product);
            $product->review_ave = round($rate['recommend_avg']);
            $product->review_cnt = intval($rate['review_count']);
        //    $Products[$i] = $product;
        }


        return $Products;
    }

    public function getSupplierCategories()
    {
        $categoryRepository = $this->containerInterface->get(CategoryRepository::class);
        $categories = $categoryRepository->getListCategoryForSupplier(env('サロン様仕入れ'));
        if ($categories) {
            $categoryChildren = $categories[0]->getSelfAndDescendants();
            foreach ($categoryChildren as $categoryChild) {
                $hiddenCategories[] = $categoryChild->getId();
            }
        }

        return $hiddenCategories;
    }
}
