<?php

namespace Customize\Repository;

use Customize\Entity\AccessLog;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, AccessLog::class);
    }
}