<?php

namespace Customize\Repository;

use Customize\Entity\Brand;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends AbstractRepository
{

    /**
     * @var ProductRepository
     */
    protected $productRepository;

    public function __construct(
        RegistryInterface $registry,
        ProductRepository $productRepository
    )
    {
        parent::__construct($registry, Brand::class);
        $this->productRepository = $productRepository;
    }

    /**
     * ブランドを保存する.
     *
     * @param  Brand $brand ブランド
     */
    public function save($brand)
    {
        if (!$brand->getId()) {
            $sortNoTop = $this->findOneBy([], ['sort_no' => 'DESC']);
            $sort_no = 0;
            if (!is_null($sortNoTop)) {
                $sort_no = $sortNoTop->getSortNo();
            }

            $brand->setSortNo($sort_no + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($brand);
        $em->flush($brand);
    }

    public function getList()
    {
        $qb = $this->createQueryBuilder('t')->orderBy('t.sort_no', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getAvailableBrands() 
    {
        $qb = $this->createQueryBuilder('b')->orderBy('b.sort_no', 'DESC')
                                            ->groupBy('b.id')
                                            ->select('b.name, b.id, b.image');
        $brands = $qb->getQuery()->getArrayResult();
        $brands = array_map(function ($item) {
            $brand = $this->findBrandById($item['id']);
            $searchData = [
                'brand' => $brand
            ];
            $productQb = $this->productRepository->getQueryBuilderBySearchData($searchData);
            $products = $productQb->groupBy('p.id')->select('p.id')->getQuery()->getResult();
            $productCount = count($products);
            $item['product_count'] = $productCount;
            return $item;
        }, $brands);
        
        return $brands;                         
    }

    public function findBrandById($id) {
        $em = $this->getEntityManager();

        $brand = $em->find(Brand::class, $id);

        return $brand;
    }
    

    /**
     * ブランドを削除する.
     *
     * @param  Brand $Brand 削除対象のブランド
     */
    public function delete($Brand)
    {
        $em = $this->getEntityManager();
        $em->beginTransaction();

        $em->remove($Brand);
        $em->flush($Brand);

        $em->commit();
    }
}