<?php

namespace Customize\Repository;

use Eccube\Entity\Category;
use Eccube\Entity\OrderItem;
use Eccube\Entity\ProductClass;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractRepository
{

    /**
     * @var ProductRepository
     */
    protected $productRepository;

    public function __construct(
        RegistryInterface $registry,
        ProductRepository $productRepository
    )
    {
        parent::__construct($registry, Category::class);
        $this->productRepository = $productRepository;
    }

    /**
     * ブランドを保存する.
     *
     * @param  Category $category ブランド
     */
    public function save($category)
    {
        if (!$category->getId()) {
            $sortNoTop = $this->findOneBy([], ['sort_no' => 'DESC']);
            $sort_no = 0;
            if (!is_null($sortNoTop)) {
                $sort_no = $sortNoTop->getSortNo();
            }

            $category->setSortNo($sort_no + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($category);
        $em->flush($category);
    }

    public function getList()
    {
        $qb = $this->createQueryBuilder('t')->orderBy('t.sort_no', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getAvailableCategories() 
    {
        $qb = $this->createQueryBuilder('c')
        ->orderBy('c.sort_no', 'DESC')
        ->addSelect('p', 'ch', 'pc', 'prod')
        ->leftJoin('c.Parent', 'p')
        ->leftJoin('c.Children', 'ch')
        ->leftJoin('c.ProductCategories', 'pc')
        ->leftJoin('pc.Product', 'prod', 'WITH', 'prod.Status = :Status')
        ->setParameter('Status', 1);

        $categories = $qb->getQuery()->getArrayResult();

        $categories = array_map(function ($item) {
            $filteredProductCategories = array_filter($item['ProductCategories'], function ($productCategory) {
                return $productCategory['Product'] !== null;
            });
            $item['product_count'] = count($filteredProductCategories);
            return $item;
        }, $categories);

        return $categories;                         
    }

    public function findCategoryById($id) {
        $em = $this->getEntityManager();

        $category = $em->find(Category::class, $id);

        return $category;
    }

    /**
     * ブランドを削除する.
     *
     * @param  Category $Category 削除対象のブランド
     */
    public function delete($Category)
    {
        $em = $this->getEntityManager();
        $em->beginTransaction();

        $em->remove($Category);
        $em->flush($Category);

        $em->commit();
    }
}
