<?php

namespace Customize\Repository;

use Customize\Entity\CLog;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Util\StringUtil;

/**
 * CLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLogRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, CLog::class);
    }
    /**
     * 全検索
     *
     * @return Products|array
     */
    public function customFindAll() #関数名(何でも良い)
    {
        $qb = $this->createQueryBuilder('p')
            ; #何でも良いがproductの頭文字を取ってます。
//        dump($qb->getQuery()->getSQL());
        $qb->orderBy('p.update_date','DESC')
            //->addSelect('c.name01 as name01')
            //->addSelect('p.*')
            
            ;

        $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }

    public function getCountPerStaff(){

        $qb = $this->createQueryBuilder('c')
            ->select('c.c_staff, count(c.c_staff) as count')
            ->groupBy('c.c_staff')
            ;
       $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }

    public function getCountPerStaffWithComparison(){
        // 取得當前日期，計算上月和本月的開始日・結束日
        $today = new \DateTime();
        $firstDayOfThisMonth = clone $today;
        $firstDayOfThisMonth->modify('first day of this month');
        $firstDayOfThisMonth->setTime(0, 0, 0);
        $lastDayOfThisMonth = clone $today;
        $lastDayOfThisMonth->modify('last day of this month');
        $lastDayOfThisMonth->setTime(23, 59, 59);
        $firstDayOfLastMonth = clone $today;
        $firstDayOfLastMonth->modify('first day of last month');
        $firstDayOfLastMonth->setTime(0, 0, 0);
        $lastDayOfLastMonth = clone $today;
        $lastDayOfLastMonth->modify('last day of last month');
        $lastDayOfLastMonth->setTime(23, 59, 59);
    
        $qb = $this->createQueryBuilder('c')
            ->select('c.c_staff, c.c_date')
            ->where('c.c_date BETWEEN :startLastMonth AND :endLastMonth OR c.c_date BETWEEN :startThisMonth AND :endThisMonth')
            ->setParameter('startLastMonth', $firstDayOfLastMonth)
            ->setParameter('endLastMonth', $lastDayOfLastMonth)
            ->setParameter('startThisMonth', $firstDayOfThisMonth)
            ->setParameter('endThisMonth', $lastDayOfThisMonth);
    
        $products = $qb
            ->getQuery() 
            ->getResult();
    
        // 整理數據並計算前月比
        $result = [];
        
        foreach($products as $product) {
            $staff = $product['c_staff'];
            $cDate = $product['c_date'];
            if ($cDate instanceof \DateTime) {
                $dateObj = $cDate;
            } else {
                $dateObj = new \DateTime($cDate);
            }
            
            if(!isset($result[$staff])) {
                $result[$staff] = ['last_month' => 0, 'this_month' => 0];
            }
            
            // 判断是否在上月范围内
            if ($dateObj >= $firstDayOfLastMonth && $dateObj <= $lastDayOfLastMonth) {
                $result[$staff]['last_month']++;
            } 
            // 判断是否在本月范围内
            elseif ($dateObj >= $firstDayOfThisMonth && $dateObj <= $lastDayOfThisMonth) {
                $result[$staff]['this_month']++;
            }
        }
        foreach($result as $staff => &$data) {
            $data['difference'] = $data['this_month'] - $data['last_month'];
        }
        return $result;
    }
    /**
     * 取得過去一年的銷售額
     * 
     * @return array
     */
    public function getSalesPerStaffPastYear()
    {
        $oneYearAgo = (new \DateTime())->modify('-1 year');

        $qb = $this->createQueryBuilder('c')
            ->innerJoin('c.Order', 'o')
            ->select('c.c_staff, c.c_date, SUM(o.payment_total) as total_sales')
            ->where('c.c_date > :oneYearAgo')
            ->setParameter('oneYearAgo', $oneYearAgo)
            ->groupBy('c.c_staff, c.c_date')
            ->orderBy('c.c_staff, c.c_date');

        $results = $qb->getQuery()->getResult();
        
        // Process results to group by staff, year, and month
        $processedResults = [];
        foreach($results as $result) {
            $staff = $result['c_staff'];
            $cDate = $result['c_date'];
            if ($cDate instanceof \DateTime) {
                $year = (int)$cDate->format('Y');
                $month = (int)$cDate->format('m');
            } else {
                $year = (int)date('Y', strtotime($cDate));
                $month = (int)date('m', strtotime($cDate));
            }
            
            $key = $staff . '_' . $year . '_' . $month;
            if (!isset($processedResults[$key])) {
                $processedResults[$key] = [
                    'c_staff' => $staff,
                    'year' => $year,
                    'month' => $month,
                    'total_sales' => 0
                ];
            }
            $processedResults[$key]['total_sales'] += $result['total_sales'];
        }
        
        // Convert to array and sort
        $finalResults = array_values($processedResults);
        usort($finalResults, function($a, $b) {
            if ($a['c_staff'] != $b['c_staff']) {
                return $a['c_staff'] <=> $b['c_staff'];
            }
            if ($a['year'] != $b['year']) {
                return $a['year'] <=> $b['year'];
            }
            return $a['month'] <=> $b['month'];
        });
        
        return $finalResults;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c');

        if (isset($searchData['c_staff']) && StringUtil::isNotBlank($searchData['c_staff'])) {
            //移除空格
            $clean_key_multi = preg_replace('/\s+|[　]+/u', '', $searchData['c_staff']);
            $id = preg_match('/^\d{0,10}$/', $clean_key_multi) ? $clean_key_multi : null;
            $qb
                ->andWhere('c.c_staff LIKE :c_staff')
                ->setParameter('c_staff', '%'.$clean_key_multi.'%')
                ;
        }

        // Pref
        if (is_numeric($searchData['c_cate']) && $searchData['c_cate'] >= 0) {
            $qb
                ->andWhere('c.c_cate = :c_cate')
                ->setParameter('c_cate', $searchData['c_cate']);
        }

        if (is_numeric($searchData['c_status']) && $searchData['c_status'] >= 0) {
            $qb
                ->andWhere('c.c_status = :c_status')
                ->setParameter('c_status', $searchData['c_status']);
        }

        if (isset($searchData['multi']) && StringUtil::isNotBlank($searchData['multi'])) {
            //移除空格
            $qb
                ->andWhere('c.today_msg LIKE :today_msg OR c.next_msg LIKE :next_msg OR c.memo LIKE :memo')
                ->setParameter('today_msg', '%' . $searchData['multi'] . '%')
                ->setParameter('next_msg', '%' . $searchData['multi'] . '%')
                ->setParameter('memo', '%' . $searchData['multi'] . '%');
        }

        // Order By
        $qb->addOrderBy('c.update_date', 'DESC');
       $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }

}