<?php

namespace Customize\Repository;

use Customize\Entity\FaqCategory;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FaqCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqCategoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, FaqCategory::class);
    }

    public function getQueryBuilder()
    {
        $qb = $this->createQueryBuilder('fc')
            ->select('fc');

        return $qb;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->getQueryBuilder();

        if (isset($searchData['faq_category_id']) && $this->find($searchData['faq_category_id'])) {
            $qb
                ->andWhere('fc.id = :id')
                ->setParameter('id', $searchData['faq_category_id']);
        }

        if (isset($searchData['keyword'])) {
            $qb
                ->join('fc.Faqs', 'f')
                ->andWhere('f.question LIKE :keyword OR f.answer LIKE :keyword')
                ->setParameter('keyword', "%{$searchData['keyword']}%");
        }

        return $qb;
    }
}