<?php

namespace Customize\Repository;

use Customize\Entity\Faq;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends AbstractRepository
{
    /**
     * @var FaqCategoryRepository
     */
    protected $faqCategoryRepository;

    public function __construct(
        RegistryInterface $registry,
        FaqCategoryRepository $faqCategoryRepository
    )
    {
        parent::__construct($registry, Faq::class);
        $this->faqCategoryRepository = $faqCategoryRepository;
    }

    public function getQueryBuilderBySearchDataForAdmin($searchData)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('f');

        if (isset($searchData['FaqCategory'])) {
            $qb->where('f.FaqCategory = :FaqCategory')
                ->setParameter('FaqCategory', $searchData['FaqCategory']);
        }

        return $qb;
    }

    public function getListForTop()
    {
        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->where('f.display_top = true');

        return $qb->getQuery()->getResult();
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('f');

        if (isset($searchData['faq_category_id'])) {
            $FaqCategory = $this->faqCategoryRepository->find($searchData['faq_category_id']);
            if ($FaqCategory) {
                $qb
                    ->andWhere('f.FaqCategory = :id')
                    ->setParameter('id', $FaqCategory);
            }
        }

        if (isset($searchData['keyword'])) {
            $qb
                ->andWhere('f.question LIKE :keyword OR f.answer LIKE :keyword')
                ->setParameter('keyword', "%{$searchData['keyword']}%");
        }

        return $qb;
    }
}