<?php

namespace Customize\Repository;

use Customize\Entity\LiveLog;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Util\StringUtil;

/**
 * MlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiveLogRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, LiveLog::class);
    }
    /**
     * 全検索
     *
     * @return Products|array
     */
    public function customFindAll() #関数名(何でも良い)
    {
        $qb = $this->createQueryBuilder('p')
            ; #何でも良いがproductの頭文字を取ってます。
//        dump($qb->getQuery()->getSQL());
        $qb->orderBy('p.update_date','DESC')
            //->addSelect('c.name01 as name01')
            //->addSelect('p.*')
            
            ;

        $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }

    /**
     * 
     */
    public function getCountPerStaff(){

        $qb = $this->createQueryBuilder('c')
            ->select('c.c_staff, count(c.c_staff) as count')
            ->groupBy('c.c_staff')
            ;
       $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }


    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c');

        if (isset($searchData['c_staff']) && StringUtil::isNotBlank($searchData['c_staff'])) {
            //スペース除去
            $clean_key_multi = preg_replace('/\s+|[　]+/u', '', $searchData['c_staff']);
            $id = preg_match('/^\d{0,10}$/', $clean_key_multi) ? $clean_key_multi : null;
            $qb
                ->andWhere('c.c_staff LIKE :c_staff')
                ->setParameter('c_staff', '%'.$clean_key_multi.'%')
                ;
        }

        // Pref
        //if (is_numeric($searchData['c_cate']) && $searchData['c_cate'] >= 0) {
        //    $qb
        //        ->andWhere('c.c_cate = :c_cate')
        //        ->setParameter('c_cate', $searchData['c_cate']);
        //}

        // date

        if (isset($searchData['c_date']) && $searchData['c_date']) {
            //var_dump($searchData);
            //exit;
            $qb
                ->andWhere('c.c_date = :c_date')
                ->setParameter('c_date', date('Y-m-d', strtotime($searchData['c_date']->format('Y-m-d'))));
        }

        // Order By
        $qb->addOrderBy('c.c_date', 'DESC');
        $qb->addOrderBy('c.update_date', 'DESC');

        $products = $qb
            ->getQuery() #作成したクエリを取得
            ->getResult(); #実行
        return $products;
    }

}