<?php

namespace Customize\Repository;

use Customize\Entity\PointLog;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PointLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointLogRepository extends AbstractRepository
{

    public function __construct(
        RegistryInterface $registry
    )
    {
        parent::__construct($registry, PointLog::class);
    }

}