<?php

namespace Customize\Repository;

use Doctrine\DBAL\Tools\Dumper;
use Eccube\Entity\Category;
use Eccube\Entity\Master\OrderStatus;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\ProductRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRepository extends AbstractRepository
{

    /**
     * @var ProductRepository
     */
    protected $productRepository;

    public function __construct(
        RegistryInterface $registry,
        ProductRepository $productRepository
    )
    {
        parent::__construct($registry, Category::class);
        $this->productRepository = $productRepository;
    }

    /**
     * ブランドを保存する.
     *
     * @param  Category $category ブランド
     */

    public function getRankingProductByCategories() 
    {
        $qb = $this->createQueryBuilder('c')
        ->innerJoin('c.ProductCategories', 'pct')
        ->innerJoin('pct.Product', 'p')
        ->where('c.hierarchy = :hierarchy')
        ->setParameter('hierarchy', 1)
        ->orderBy('c.sort_no','ASC')
        ->groupBy('p.id');
        $categories = $qb->getQuery()->getResult();
        $data = [];
        foreach($categories as $category){
            $qbOi = $this->getEntityManager()->createQueryBuilder()
            ->select('p.id AS product_id, COUNT(oi.id) AS order_count')
            ->from('Eccube\Entity\OrderItem', 'oi')
            ->join('oi.Product', 'p')
            ->innerJoin('oi.Order', 'o')
            ->innerJoin('p.ProductCategories', 'pct')
            ->where('pct.Category = :category')
            ->andWhere('o.OrderStatus = (:status)')
            ->setParameter('category', $category->getId())
            ->setParameter('status', OrderStatus::DELIVERED)
            ->setMaxResults(10)
            ->orderBy('order_count', 'DESC')
            ->groupBy('p.id');
            $orderItemResults = $qbOi->getQuery()->getResult();
            $data[] = [
                'category' => $category,
                'products' => $orderItemResults
            ];
        }

        return $data;

    }

    
}
