<?php

namespace Plugin\A8SalesTag4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\A8SalesTag4\Entity\Tracking;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Tracking::class);
    }

    private function createKey($pid) {
	    return '_a8_'.$pid;
    }

    private function isCompletedKey() {
	    return '_a8_is_completed';
    }

    private function makecookie($key, $param){
        $ar_host = explode(".", $_SERVER["HTTP_HOST"]);
        $firstval = array_shift($ar_host);
        $domain = ".".implode(".",$ar_host);
        $expires = time() + (3600 * 24 * 365 * 5);
        return setcookie($key, $param, $expires, "/", $domain);
    }

    /**
     * @param string $pid
     *
     * @return string
     */
    public function get($pid)
    {
        $key = $this->createKey($pid);
        $ret = (isset($_COOKIE[$key])) ? $_COOKIE[$key] : "";
        return $ret;
    }

    /**
     * @param string $eid
     *
     * @return string
     */
    public function findPidsBy($eid)
    {
        $e_key = $this->createKey($eid);
        $keys = array_map(function($p_key) {
            return substr($p_key, 4);
        }, array_keys(
            array_filter($_COOKIE, function($k) use ($e_key) {
                return 0 === strpos($k, $e_key);
            }, ARRAY_FILTER_USE_KEY)));
        $pids = implode(",", $keys);
        return $pids;
    }

    /**
     * @param string $a8
     *
     * @return null
     */
    public function saveParam($a8)
    {
        if (empty($a8)) {
            return;
        }
        $pid = substr($a8, -15);
        if ($pid[0] != 's') {
            return;
        }
        $key = $this->createKey($pid);
        $this->makecookie($key, $a8);
    }

    /**
     * @return boolean $is_completed
     */
    public function isCompleted()
    {
        $key = $this->isCompletedKey();
	$is_completed = isset($_SESSION[$key]) ? $_SESSION[$key] : false;
	return $is_completed;
    }

    /**
     * @return null
     */
    public function completed()
    {
        $key = $this->isCompletedKey();
	$_SESSION[$key] = true;
    }

    /**
     * @return null
     */
    public function initCompletion()
    {
        $key = $this->isCompletedKey();
	$_SESSION[$key] = false;
    }
}
