<?php
/*
* Plugin Name : uc_slide_cbd_sp
*/

namespace Plugin\uc_slide_cbd_sp\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\uc_slide_cbd_sp\Entity\uc_slide_cbd_spData;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * uc_slide_cbd_spImage Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uc_slide_cbd_spDataRepository extends AbstractRepository
{
    /**
     * uc_slide_cbd_spDataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, uc_slide_cbd_spData::class);
    }

    /**
     * @param int $id
     *
     * @return null|uc_slide_cbd_spData
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|uc_slide_cbd_spData
     */
    public function getImages()
    {
        return $this->findAll();
    }
}
