<?php
/*
* Plugin Name : [code]
*/

namespace Plugin\[code]\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\[code]\Entity\[code]Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * [code] Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class [code]ConfigRepository extends AbstractRepository
{
    /**
     * [code]Repository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, [code]Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|[code]Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
