<?php
/*
* Plugin Name : [code]
*/

namespace Plugin\[code]\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\[code]\Entity\[code]Data;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * [code]Image Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class [code]DataRepository extends AbstractRepository
{
    /**
     * [code]DataRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, [code]Data::class);
    }

    /**
     * @param int $id
     *
     * @return null|[code]Data
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * id !== 1 をすべて取得
     *
     * @return null|[code]Data
     */
    public function getImages()
    {
        return $this->findAll();
    }
}
